### ISSUE TITLE
[Question] Mono support

### ISSUE THREAD

**Issue by ghost** [Banane9/IronWren#1]
Will IronWren work on Mono? I am thinking of integrating it into my application but it must run on both Microsoft .NET and Mono

**Comment by Banane9** [comment]
Well, supposedly it should work... I sadly don't have a linux machine to test on, and a VM runs painfully slow, but what I've found is that mono currently crashes with a DllNotFoundException regarding the DllImport attributes used for P/Invoking the C-DLL.

I have the feeling this is just due to not specifying the extension for the file. Currently the code is for `Native/wren`, but mono isn't finding a file called `wren` (because it's actually `wren.dll`).

**Comment by ghost** [comment]
We probably have to recompile to something like `wren.so`.
A fully .NET implementation of Wren would be better suited to this rather than one that marshals between Wren native and .NET.
